### ISSUE TITLE
Double-reference to array head

### ISSUE THREAD

**Issue by elodg** [Xilinx/embeddedsw#110]
https://github.com/Xilinx/embeddedsw/blob/920eed79b3fdf1a638ab4a9dbe264bbde5f0c6bd/XilinxProcessorIPLib/drivers/v_hdmitxss/examples/xhdmi_example/dp159.c#L64

Should be
`(u8 *)buf`
all throughout the code

**Comment by colin-foster-in-advantage** [comment]
Couldn't it just be "buf", or "&buf[0]" to avoid casting?

**Comment by elodg** [comment]
I was surprised to find out that &buf is actually correct, but looks very odd to me. For &buf and buf array decay happens implicitly, so no cast is necessary. &buf[0] is has the correct type from the start.
