### ISSUE TITLE
XSecure_RsaDecrypt vs XSecure_RsaOperation

### ISSUE THREAD

**Issue by JacobBarthelmeh** [Xilinx/embeddedsw#125]
Am updating support of Xilsecure API calls to 2019 and have ran into a fail case with one of my tests. Before tracking it down too far I have a question, is XSecure_RsaOperation(&rsa, in, out, XSECURE_RSA_SIGN_DEC, 512) equivalent to the older API XSecure_RsaDecrypt(&rsa, in, out)?

**Comment by vnsldurg** [comment]
Hi @JacobBarthelmeh 

The XSecure_RsaDecrypt() API has been deprecated from 2019.1 and the equivalent to this API XSecure_RsaPublicEncrypt(), please replace your XSecure_RsaDecrypt() APIs with XSecure_RsaPublicEncrypt() calls

Please refer to https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/18842278/xilsecure+Library 2019.1 change list for more details on different changes.

Regards
Durga
