### ISSUE TITLE
Clock Wizard (AXI4 dynamic config) only runs on Versal

### ISSUE THREAD

**Issue by bindebende** [Xilinx/embeddedsw#136]
XClk_Wiz_SetRate function has a condition, which returns with XST_SUCCESS if the platform is **not** Versal.

Is this intentional? (I'm trying to run it on zynq) 
Searched the whole repository for the same condition and this is the only one.

https://github.com/Xilinx/embeddedsw/blob/a60c084a0862559e2fa58fd4c82b0fe39b923e33/XilinxProcessorIPLib/drivers/clk_wiz/src/xclk_wiz.c#L190-L191

**Comment by shubhrajyoti1** [comment]
The programing model for versal and zynqmp is different. Currently we support only versal for changing rates For zynq/ zynqmp  support is added in 2020.2

**Comment by bindebende** [comment]
Thank you for clarifying.
