### ISSUE TITLE
Xilffs curious code

### ISSUE THREAD

**Issue by raiatea** [Xilinx/embeddedsw#154]
Hello, I have two questions about the library Xilffs

 1) In SDK, what is the correct way to configure the options of the library (for example set FF_USE_FIND to enable f_findnext) ?
Should one directly edit the file ffconf.h ?

 2) f_findnext() has not the behaviour I expect.
Here is a simple code to browse the files in a directory

res = f_findfirst(&dp, &nfo, "", "*");
while (res == FR_OK)
{
	// use nfo
	res = f_findnext(&dp, &nfo);
}

One would expect that it would stop when res = FR_NO_FILE, but in fact, res is always FR_OK, the loop is infinite.

In ff.c, function f_findnext() calls f_readdir() that seems to always return FR_OK:

line 4542 if (res == FR_NO_FILE) res = FR_OK; /* Ignore end of directory */
line 4547 if (res == FR_NO_FILE) res = FR_OK; /* Ignore end of directory now */

A workaround to break it is

while (res == FR_OK)
{
	if (nfo.fname[0] == 0)
		break;
	// use nfo
	res = f_findnext(&dp, &nfo);
}

Is the library f_readdir() code correct ?
Then what is a correct customer code to browse the files in a directory ?

**Comment by saikrishnapotthuri** [comment]
Hi,

Please find the answers below for your queries
1. In SDK, what is the correct way to configure the options of the library (for example set FF_USE_FIND to enable f_findnext) ?
Should one directly edit the file ffconf.h ?
>> For few configurations like FF_USE_LFN, FF_FS_READONLY etc., which we used in most of our standard use cases can be configured through SDK/Vitis GUI. For FF_USE_FIND we don't have any GUI option to configure, so you can configure the option by editing the ffconf.h file.
2. f_findnext() has not the behaviour I expect.
>> It is the correct behavior and that is how f_readdir() is developed. 
When all items in the directory have been read and no item to read, a null string is stored into the fno->fname[] without any error. We must rely on fno.fname[0] == 0 for FR_NO_FILE or end of the directory.
Please refer the below links
http://elm-chan.org/fsw/ff/doc/findfirst.html
http://elm-chan.org/fsw/ff/doc/readdir.html
