### ISSUE TITLE
xcanfd_intr_example.c TxFrame and RxFrame size question

### ISSUE THREAD

**Issue by sarenameas** [Xilinx/embeddedsw#157]
Hello,

In xcanfd_intr_example.c the TxFrame and RxFrame variables are arrays of 32 bit unsigned integers where the array is sized `XCANFD_MAX_FRAME_SIZE_IN_BYTES`. `XCANFD_MAX_FRAME_SIZE_IN_BYTES` is equal to 72. 
72 is the maximum CANFD frame length in bytes. Ok that sort of makes sense because there are 64 bytes of data and then there are 4 bytes for the ID register and 4 bytes for the DLC register, so that is 72 bytes total.
BUT 72 is a length in bytes, so why are we sizing the TxFrame and RxFrame array by 72? I think that TxFrame and RxFrame should instead 18 in length.

Current code (https://github.com/Xilinx/embeddedsw/blob/master/XilinxProcessorIPLib/drivers/canfd/examples/xcanfd_intr_example.c#L163):
```
static u32 TxFrame[XCANFD_MAX_FRAME_SIZE_IN_BYTES];
static u32 RxFrame[XCANFD_MAX_FRAME_SIZE_IN_BYTES];
```

Proposal:

```
static u32 TxFrame[XCANFD_MAX_FRAME_SIZE_IN_BYTES / 4];
static u32 RxFrame[XCANFD_MAX_FRAME_SIZE_IN_BYTES / 4];
```

Am I missing something here?

Thanks!
Sarena

**Comment by sneeli-git** [comment]
These buffers are global buffers, Just for sending and receiving the frames.
We are not using "XCANFD_MAX_FRAME_SIZE_IN_BYTES" macro in driver.
It won't impact any functionality difference.
In TxFrame/RxFrame we are filling/reading based on DLC length(max DLC 16).
so we are not filling more than 18(DATA+ID+DLC) rows in array.

we agree size should be (XCANFD_MAX_FRAME_SIZE_IN_BYTES / 4), Will update in next release.

**Comment by sarenameas** [comment]
Thank you!
