### ISSUE TITLE
PPP_SUPPORT wont turn on 

### ISSUE THREAD

**Issue by Sujjan19** [Xilinx/embeddedsw#258]
The PPP_SUPPORT wont turn on, even after changing the value from '0' to '1', after the build completes, it changes back to '0'
![Screenshot 2023-07-20 164510](https://github.com/Xilinx/embeddedsw/assets/86064602/490d17f2-376f-4460-bc0e-1b3a77647b77)

**Comment by anirudha1977** [comment]
Hi,
The include directory is recreated for each BSP build.
Instead of changing it here, please change it at: libsrc/lwip/src folder.

Thanks
