### ISSUE TITLE
Macro expansions with missing parantheses in xqspips.h

### ISSUE THREAD

**Issue by asahin24** [Xilinx/embeddedsw#289]
In **xqspips.h**
In all macro expansions, **InstancePtr** is wrapped up with paranthesis except
- XQspiPs_Enable
- XQspiPs_Disable
- XQspiPs_GetTXWatermark
- XQspiPs_GetRXWatermark

All macro expansions (except these) can be called with argument "&QspiInstance".

```c
//Example:
XqspiPs QspiInstance;
XQspiPs_GetLqspiConfigReg(&QspiInstance)
```

If I call these macro expansions the same way, compiler raises Error :

> **base operand of '->' has non-pointer type 'XQspiPs'	xqspips.h**

I should call them with extra paranthesis:
```c
XQspiPs_Disable((&QspiInstance));
```

It took some time for me to realize the problem.
It would be nice to be able to call all of them the same way

**Comment by Amit-Kumar-Mahapatra** [comment]
Hello @asahin24 

Thank you for bring this to our notice. Its a vaild issue and we will fix in next release
