### ISSUE TITLE
PMUFW fails to build with REMOVE_GPIO_FROM_NODE_RESET_INFO, IDLE_PERIPHERALS, ENABLE_NODE_IDLING

### ISSUE THREAD

**Issue by vamoirid** [Xilinx/embeddedsw#291]
There are various parts of code in the `XilinxProcessorIPLib/drivers/` like `gpiops` and `iicps` directories which are still using the type UINTPTR. This results in failed compilations of the PMUFW. 

The flags are taken from this guide: https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/18841820/Zynq+UltraScale+MPSoC+Restart+solution

Could you please provide with a patch solving these issues?

**Comment by vamoirid** [comment]
Any updates?

**Comment by gsrinivasgoud** [comment]
@vamoirid We are unable to reproduce the issue at our end.
May I know which release build you are using and also apart from these flags any other changes ate required to preproduce the issue

**Comment by ManikantaGuntupalli** [comment]
Hi @vamoirid,
Please try with attached patch, it fixes PMUFW build issue and let us know status.

[0001-zynqmp_pmufw-Fix-compilation-issue.patch](https://github.com/Xilinx/embeddedsw/files/14718289/0001-zynqmp_pmufw-Fix-compilation-issue.patch)

**Comment by vamoirid** [comment]
Sorry, I forgot to reply, it indeed fixes the issue, thanks! Will you solve it for the next releases as well?
