### ISSUE TITLE
axivdma driver is missing Example

### ISSUE THREAD

**Issue by Bethexone** [Xilinx/embeddedsw#298]
vitis 2023.2  vitis unifed IDE
在C:\Xilinx\Vitis\2023.2\data\embeddedsw\XilinxProcessorIPLib\drivers\axivdma_v6_14\examples\readme.txt中明确提供了3个例程文件，但是在vitis unifed IDE中只显示了一个
XilinxProcessorIPLib/drivers/axivdma/examples/CMakeLists.txt

**Comment by Coding-xinxiangwanji2017** [comment]
Hi，您好：    我收到了您邮件，等我看完邮件以后，第一时间给您回复。

**Comment by Bethexone** [comment]
<img width="419" alt="屏幕截图 2024-05-13 105201" src="https://github.com/Xilinx/embeddedsw/assets/105570420/4c6ee98c-f93b-44ec-9fe5-e333c5375843">

**Comment by HariniKatakamX** [comment]
Hi @Bethexone There are only two examples for VDMA - selftest and interrupt. The former is visible in your screenshot. The latter requires an interrupt to be connected in the design. Can you please check your design to make sure a valid interrupt is connected to GIC or INTC controller?

**Comment by Bethexone** [comment]
thank，You're right. I saw the problem












Be&nbsp;the&nbsp;one
***@***.***


---Original---
From: ***@***.***&gt;
Date: Tue, May 14, 2024 11:53 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Xilinx/embeddedsw] axivdma driver is missing Example (Issue#298)




 
Hi @Bethexone There are only two examples for VDMA - selftest and interrupt. The former is visible in your screenshot. The latter requires an interrupt to be connected in the design. Can you please check your design to make sure a valid interrupt is connected to GIC or INTC controller?
