### ISSUE TITLE
add function prototype for msleep() in sleep.h

### ISSUE THREAD

**Issue by digitalnumeric** [Xilinx/embeddedsw#324]
msleep() is listed as supported by XilTimer, but its prototype is missing from sleep.h. 
[Standalone Library Documentation: BSP and Libraries Document Collection (UG643)](https://docs.amd.com/r/en-US/oslib_rm/msleep)

XilTimer.c has a msleep() function: [xiltimer.c on Github](https://github.com/Xilinx/embeddedsw/blob/master/lib/sw_services/xiltimer/src/xiltimer.c)
`void msleep(unsigned long mseconds) {
    XilTimer_Sleep(mseconds, XTIMER_DELAY_MSEC);
}`

msleep()'s prototype is missing from both XilTimer's sleep.h and common's sleep.h:
[XilTimer's sleep.h on Github](https://github.com/Xilinx/embeddedsw/blob/master/lib/sw_services/xiltimer/src/sleep.h)
[common's sleep.h on Github](https://github.com/Xilinx/embeddedsw/blob/master/lib/bsp/standalone/src/common/sleep.h)

This can be corrected by adding the msleep() prototype to both the above files as done in the attached patch file:
[msleep.patch](https://github.com/user-attachments/files/17880080/msleep.patch)

Reference to where this was reported on the forums earlier this year:
[Vitis Unified msleep() function missing from sleep.h but present in xiltimer.c](https://support.xilinx.com/s/question/0D54U00008CPFsASAX/vitis-unified-msleep-function-missing-from-sleeph-but-present-in-xiltimerc?language=en_US)

Reference to the original issue on github which was closed and replaced by this new issue with a patch file:
[msleep has no function prototype #305](https://github.com/Xilinx/embeddedsw/issues/305)

**Comment by anirudha1977** [comment]
Thanks for reporting this.
Sorry for this from our end.
We will fix this in the next release. We have created an internal tracking item for this.

**Comment by digitalnumeric** [comment]
Sound good.  Thank you.

**Comment by digitalnumeric** [comment]
Based on a reply to https://github.com/Xilinx/embeddedsw/issues/305 and a 2nd look at Vitis 2024.2 it appears it is there in all the files where it is intended to be.
