### ISSUE TITLE
Build instructions for standalone driver examples

### ISSUE THREAD

**Issue by moritz89** [Xilinx/embeddedsw#33]
Hi, I am trying to build the example for the AXI DMA driver for a reference in how to use it. The make files are incomplete and probably bootstrapped by an external build system. Also, attempts to add all dependencies manually and setting the include paths, ended in not having the driver libs to link against. Therefore, would it be possible to add:

1. A guide how to build the drivers themselves
2. And examples
3. A link in the source to further documentation?

**Comment by sri-vemula** [comment]
The drivers cannot be built outside Xilinx's Software Development Kit (SDK).
